routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/verified', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);
Route::get('/home', 'HomeController@index');
Route::get('/logout', 'Auth\LoginController@logout');

Route::get('images/user/{filename}', function ($filename) {
$path = storage_path('app/public/user/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('images/blog/{filename}', function ($filename) {
    $path = storage_path('app/public/blog/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('report/{filename}', function ($filename) {
    $path = storage_path('app/public/report/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('banner/{filename}', function ($filename) {
    $path = storage_path('app/public/banner/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('description/{filename}', function ($filename) {
    $path = storage_path('app/public/description/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('certificate/{filename}', function ($filename) {
    $path = storage_path('app/public/certificate/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('product/{filename}', function ($filename) {
    $path = storage_path('app/public/product/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});


// Front pages
Route::get('/', 'HomeController@index')->name('home');
Route::get('/tentang-kami', 'HomeController@about')->name('tentang-kami');
Route::get('/faq', 'HomeController@faq')->name('faq');
Route::get('/layanan', 'HomeController@service')->name('layanan');

// Blog pages
Route::get('/blog', 'BlogController@index')->name('blog.index');
Route::get('/blog/{title}', 'BlogController@show')->name('blog.show');

// Admin routes
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/invest', 'AdminController@invest')->name('admin.invest');
    Route::get('/transactions', 'AdminController@transaction')->name('admin.transaction');

    // User prefixed
    Route::group(['prefix' => 'user'], function () {
        Route::get('/', 'Admin\UserController@index')->name('admin.user');
        Route::delete('/delete/{user}', 'Admin\UserController@destroy')->name('admin.user.destroy');
        Route::get('/detail/{user}', 'Admin\UserController@detail')->name('admin.user.detail');
        Route::get('/order/updates', 'Admin\UserController@orderUpdates')->name('admin.user.order.updates');
        Route::get('/notification/{user}', 'Admin\UserController@notification')->name('admin.user.notification');

        // order
        Route::get('/order/{user}', 'Admin\UserController@order')->name('admin.user.order');
        Route::get('/order/{user}/edit/{order}', 'Admin\OrderController@orderEdit')->name('admin.user.order.edit');
        Route::put('/order/{user}/edit/{order}', 'Admin\OrderController@orderUpdate')->name('admin.user.order.update');
        Route::put('/order/{user}/editPrice/{order}', 'Admin\OrderController@orderPriceUpdate')->name('admin.user.order.update.price');
        Route::get('/order/{user}/report/{order}', 'Admin\OrderController@report')->name('admin.user.order.report');
        Route::get('/order/{user}/report/{order}/create', 'Admin\OrderController@reportCreate')->name('admin.user.order.report.create');
        Route::post('/order/{user}/report/{order}/create', 'Admin\OrderController@reportStore')->name('admin.user.order.report.store');
        Route::get('/order/{user}/report/{order}/edit/{report}', 'Admin\OrderController@reportEdit')->name('admin.user.order.report.edit');
        Route::put('/order/{user}/report/{order}/edit/{report}', 'Admin\OrderController@reportUpdate')->name('admin.user.order.report.update');
        Route::delete('/order/{user}/report/{order}/delete/{report}', 'Admin\OrderController@reportDestroy')->name('admin.user.order.report.destroy');

        // location
        Route::get('/order/{user}/location/{order}', 'Admin\LocationController@index')->name('admin.user.order.location');
        Route::get('/order/{user}/location/{order}/create', 'Admin\LocationController@create')->name('admin.user.order.location.create');
        Route::post('/order/{user}/location/{order}/store', 'Admin\LocationController@store')->name('admin.user.order.location.store');
        Route::get('/order/{user}/location/{order}/edit/{location}', 'Admin\LocationController@edit')->name('admin.user.order.location.edit');
        Route::put('/order/{user}/location/{order}/edit/{location}', 'Admin\LocationController@update')->name('admin.user.order.location.update');
        Route::delete('/order/{user}/location/{order}/delete/{location}', 'Admin\LocationController@destroy')->name('admin.user.order.location.destroy');
        
        // balance
        Route::get('/balance/{user}', 'Admin\BalanceController@index')->name('admin.user.balance');
        
        // table
        Route::get('/table', 'Admin\UserController@table')->name('admin.user.table');
        Route::get('/order/{user}/table', 'Admin\UserController@orderTable')->name('admin.user.order.table');
        Route::get('/balance/{user}/table', 'Admin\BalanceController@table')->name('admin.user.balance.table');
        Route::get('/notification/{user}/table', 'Admin\UserController@notificationTable')->name('admin.user.notification.table');
        Route::get('/order/{user}/report/{order}/table', 'Admin\OrderController@reportTable')->name('admin.user.order.report.table');

        // notification
        Route::get('/notification/{user}/create', 'Admin\NotificationController@create')->name('admin.user.notification.create');
        Route::post('/notification/{user}/post', 'Admin\NotificationController@store')->name('admin.user.notification.store');
        Route::delete('/notification/{user}/delete/{notification}', 'Admin\NotificationController@destroy')->name('admin.user.notification.destroy');
    });
    
    // Tree
    Route::resource('trees', 'Admin\TreeController')->except(['show']);

    // Product
    Route::get('trees/{tree}/products/table', 'Admin\ProductController@table')->name('admin.tree.product.table');
    Route::get('trees/{tree}/products', 'Admin\ProductController@index')->name('admin.tree.product.index');
    Route::get('trees/{tree}/products/create', 'Admin\ProductController@create')->name('admin.tree.product.create');
    Route::post('trees/{tree}/products/create', 'Admin\ProductController@store')->name('admin.tree.product.store');
    Route::get('trees/{tree}/products/edit/{product}', 'Admin\ProductController@edit')->name('admin.tree.product.edit');
    Route::put('trees/{tree}/products/edit/{product}', 'Admin\ProductController@update')->name('admin.tree.product.update');
    Route::delete('trees/{tree}/products/destroy/{product}', 'Admin\ProductController@destroy')->name('admin.tree.product.destroy');

    // Simulation
    Route::get('trees/{tree}/products/{product}/simulation/table', 'Admin\SimulationController@table')->name('admin.tree.product.simulation.table');
    Route::get('trees/{tree}/products/{product}/simulation', 'Admin\SimulationController@index')->name('admin.tree.product.simulation.index');
    Route::get('trees/{tree}/products/{product}/simulation/create', 'Admin\SimulationController@create')->name('admin.tree.product.simulation.create');
    Route::post('trees/{tree}/products/{product}/simulation/create', 'Admin\SimulationController@store')->name('admin.tree.product.simulation.store');
    Route::get('trees/{tree}/products/{product}/simulation/{simulation}/edit', 'Admin\SimulationController@edit')->name('admin.tree.product.simulation.edit');
    Route::put('trees/{tree}/products/{product}/simulation/{simulation}/edit', 'Admin\SimulationController@update')->name('admin.tree.product.simulation.update');
    Route::delete('trees/{tree}/products/{product}/simulation/{simulation}/destroy', 'Admin\SimulationController@destroy')->name('admin.tree.product.simulation.destroy');

    // Withdraw
    Route::group(['prefix' => 'withdraw'], function () {

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
      'tree_id',
      'name',
      'tree_quantity',
      'description',
      'available',
      'price',
      'img_black',
      'img_white',
      'img_background'
    ];

    public function tree()
    {
        return $this->belongsTo('App\Tree');
    }

    public function orders()
    {
        return $this->hasMany('App\Order');
    }

    public function simulations()
    {
        return $this->hasMany('App\Simulation');
    }
}

resources/views/admin/product/form.blade.php
@extends('layouts.admin')

@section('breadcrumbs')
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="{{ route('admin.dashboard') }}">{{ __('Dashboard') }}</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{{ route('trees.index') }}">{{ __('Pohon') }}</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{{ route('admin.tree.product.index', [$tree]) }}">{{ __('Tabungan') }}</a>
    </li>
    <li class="breadcrumb-item active">
        {{ isset($product) ? __('Edit') : __('Tambah') }}
    </li>
</ol>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card mb-3">
            <div class="card-header">
                {{ isset($product) ? 'Edit' : 'Create' }} Product
            </div> <!-- card header -->

            <div class="card-body">
                <form action="{{ isset($product) ? route('admin.tree.product.update', ['tree' => $tree, 'product' => $product]) : route('admin.tree.product.store', ['tree' => $tree]) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @if(isset($product))
                        @method('PUT')
                    @else
                        @method('POST')
                    @endif

                    <div class="form-group row">
                        <label for="name" class="col-md-3">{{ __('Nama') }}</label>
                        <div class="col-md-6">
                            <input type="text" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" value="{{ isset($product) ? $product->name : old('name') }}">
                            @if($errors->has('name'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="description" class="col-md-3">{{ __('Deskripsi') }}</label>
                        <div class="col-md-6">
                            <textarea name="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}">{{ isset($product) ? $product->description : old('description') }}</textarea>
                            @if($errors->has('description'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('description') }}</strong>
                            </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="tree_quantity" class="col-md-3">{{ __('Jumlah Pohon') }}</label>
                        <div class="col-md-6">
                            <input type="number" name="tree_quantity" class="form-control{{ $errors->has('tree_quantity') ? ' is-invalid' : '' }} col-md-4" value="{{ isset($product) ? $product->tree_quantity : old('tree_quantity') }}">
                            @if($errors->has('tree_quantity'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('tree_quantity') }}</strong>
                            </span>
                            @endif
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <label for="price" class="col-md-3">{{ __('Harga') }}</label>
                        <div class="col-md-6">
                            <input type="text" name="price" class="currency form-control{{ $errors->has('price') ? ' is-invalid' : '' }} col-md-4" value="{{ isset($product) ? $product->price : old('price') }}">
                            @if($errors->has('price'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('price') }}</strong>
                            </span>
                            @endif
                        </div>
                    </div>

                    @if (isset($product->img_black))
                    <div class="form-group row">
                        <div class="col-md-3"></div>
                        <div class="col-md-6">
                            <img src="{{ $product->img_black }}" class="img-fluid img-thumbnail">
                        </div>
                    </div>
                    @endif
                    <div class="form-group row">
                        <label for="img_black" class="col-md-3">{{ __('Img Black') }}</label>
                        <div class="col-md-6">
                            <input type="file" name="img_black" class="form-control{{ $errors->has('img_black') ? ' is-invalid' : '' }}">
                            @if($errors->has('img_black'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('img_black') }}</strong>
                            </span>
                            @endif  
                        </div>
                    </div>

                    @if (isset($product->img_white))
                    <div class="form-group row">
                        <div class="col-md-3"></div>
                        <div class="col-md-6">
                            <img src="{{ $product->img_white }}" class="img-fluid img-thumbnail">
                        </div>
                    </div>
                    @endif
                    <div class="form-group row">
                        <label for="img_white" class="col-md-3">{{ __('Img White') }}</label>
                        <div class="col-md-6">
                            <input type="file" name="img_white" class="form-control{{ $errors->has('img_white') ? ' is-invalid' : '' }}">
                            @if($errors->has('img_white'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('img_white') }}</strong>
                            </span>
                            @endif  
                        </div>
                    </div>

                    @if (isset($product->img_background))
                    <div class="form-group row">
                        <div class="col-md-3"></div>
                        <div class="col-md-6">
                            <img src="{{ $product->img_background }}" class="img-fluid img-thumbnail">
                        </div>
                    </div>
                    @endif
                    <div class="form-group row">
                        <label for="img_background" class="col-md-3">{{ __('Img Background') }}</label>
                        <div class="col-md-6">
                            <input type="file" name="img_background" class="form-control{{ $errors->has('img_background') ? ' is-invalid' : '' }}">
                            @if($errors->has('img_background'))
                            <span class="invalid-feedback">
                                <strong>{{ $errors->first('img_background') }}</strong>
                            </span>
                            @endif  
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-3"></div>
                        <div class="col-md-6">
                            <input type="submit" class="btn btn-success" value="Submit">
                        </div>
                    </div>

                </form>
            </div> <!-- card body -->
        </div> <!--card -->
    </div> <!-- col-12 -->
</div> <!-- row -->
@endsection

resources/views/admin/product/index.blade.php
@extends('layouts.admin')

@section('breadcrumbs')
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="{{ route('admin.dashboard') }}">{{ __('Dashboard') }}</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{{ route('trees.index') }}">{{ __('Pohon') }}</a>
    </li>
    <li class="breadcrumb-item active">
        {{ __('Tabungan') }}
    </li>
</ol>
@endsection

@section('content')
<div class="row">
    <div class="col-12">
        <div class="card mb-3">
            <div class="card-header">
                {{ __('Tabungan') }}
                <a href="{{ route('admin.tree.product.create', [$tree]) }}" class="btn btn-info float-right">
                    <i class="fas fa-plus-square"></i>
                </a>
            </div> <!-- card-header -->

            <div class="card-body">
                <div class="table-responsive">
                    <table class="datatable table table-striped table-hover" data-url="{{ route('admin.tree.product.table', [$tree]) }}">
                        <thead>
                            <tr>
                                <th data-field="id">{{ __('ID') }}</th>
                                <th data-field="name">{{ __('Nama') }}</th>
                                <th data-field="tree_quantity">{{ __('Jumlah Pohon') }}</th>
                                <th data-field="description">{{ __('Deskripsi') }}</th>
                                <th data-field="price">{{ __('Harga') }}</th>
                                <th data-field="img_black">{{ __('Img Black') }}</th>
                                <th data-field="img_white">{{ __('Img White') }}</th>
                                <th data-field="img_background">{{ __('Img Background') }}</th>
                                <th data-field="action">{{ __('Aksi') }}</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div> <!-- card-body -->
        </div> <!-- card -->
    </div> <!-- col-12 -->
</div> <!-- row -->
@endsection